### PR TITLE
Adopting IntelMausi link management and structure approach

### PR DESCRIPTION
**Pull request by donatengit**
adopts/merges [IntelMausi](https://github.com/acidanthera/IntelMausi) link management and code structure approach (for further work).

It should properly handle:

- Cable plug-in/-out (including switching between various link speed partners)
- Enable/disable via macOS `Settings`
- Enable/disable via `ifconfig enX up/down`
    Enable after sleep

And, hopefully, potential issues with connection drops (not reproducible on my I211 @ B450 though).

Tested on 1Gbps ISP cable and 100Mbs router's link both forced and autonegotiated (although on 1Gbps autoneg is always enable per Intel's source).

Note: please give it ~10 seconds to reset/negotiate if your changes of link state are frequent.

### CODE REVIEW

**Comment by donatengit** [comment]
Hi Shaneee,

As far as I understand you are experiencing stability issues as well. Considering your experience of debugging will you have some time to explain the context of problems and/or provide some log outputs? If so will discord or any other messenger work?

There are 3 main potential sources of problem as far as I could get from the source.
1. EEE
2. Legacy interrupts instead of MSI-X 
3. outputPackets always returning _kIOReturnOutputSuccess_  no matter what

**Comment by donatengit** [comment]
Hey @Shaneee,
Thanks for merging. Does it mean you are going to support the driver going forward?

**Comment by Shaneee** [comment]
> Hey @Shaneee,
> Thanks for merging. Does it mean you are going to support the driver going forward?

For sure. You've made more progress than I ever could.

**Comment by donatengit** [comment]
> For sure. You've made more progress than I ever could.

Thanks, but I consider them primarily cosmetic or taken from IntelMausi. Still not clear what is wrong with X570 and trx40.

It might be the fact that the driver doesn't use MSI-X interrupts as I think vendors would reliably assume that all modern system uses it for high speed (not the legacy ones), thus not properly tested or assembled differently. 

But that's a huge change I don't have time for at the moment considering the almost absent debug capabilities. A good option would be to move the driver to user-space as forced by Apple where debug tools are all available, but that's even a bigger project since I wasn't able to find good open source examples of such drivers, nor the excessive documentation (Apple's one is very poor at the moment).

**Comment by fabiosun** [comment]
https://www.macos86.it/topic/6029-appleigb-and-intelmausi-integration/

this working perfectly on TRX40 motherboard also with both ethernet connected

image

no other versions had ever had worked for trx40 users

**Pull request merged**
